apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

metadata:
  name: eks-upgrade-demo
  region: us-east-1
  version: "1.23"
  
iam:
  withOIDC: true
  
addons:
- name: vpc-cni
  version: 1.9.3
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
- name: kube-proxy
