apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-upgrade-demo
  region: us-west-2
  version: "1.23"
  
iam:
  withOIDC: true
  
addons:
- name: vpc-cni
  version: 1.9.3
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
- name: kube-proxy
