apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-upgrade-demo
  region: us-east-1
  
vpc:
  id: "vpc-016b0cebd49931242"
  subnets:
    private:
      us-east-1a:
        id: "subnet-087c7d6627ee2b26a"
      us-east-1b:
        id: "subnet-07b74b5dc275c4e7f"

managedNodeGroups:
- name: controller
  desiredCapacity: 2
  minSize: 0
  maxSize: 3
  instanceType: m5.large
  privateNetworking: true
  labels:
    app: lbc
    
- name: app
  desiredCapacity: 2
  minSize: 0
  maxSize: 2
  instanceType: t3.medium
  privateNetworking: true
  subnets:
  - us-east-1a
  labels:
    app: tomcat
  taints:
  - key: app
    value: tomcat
    effect: NoSchedule
    
nodeGroups:
- name: app2
  desiredCapacity: 2
  minSize: 0
  maxSize: 3
  instanceType: t3.medium
  privateNetworking: true
  subnets:
  - us-east-1a
  labels:
    app: tomcat2
  taints:
  - key: app
    value: tomcat2
    effect: NoSchedule
