apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fake-hpa
  namespace: default
  labels:
    eventing.knative.dev/release: "v1.2.0"
    app.kubernetes.io/component: fake-apps
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/name: fake-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fake-deployment
  minReplicas: 1
  maxReplicas: 5
