apiVersion: v1
kind: ConfigMap
metadata:
  name: k6script
  namespace: default
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    export default function () {
      const params = {
        timeout: "2s",
      };
      http.get('http://nginx-nlb.web');
      sleep(1);
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: k6
  namespace: default
spec:
  containers:
  - image: grafana/k6:latest
    name: k6
    args:
    - run
    - --http-debug=headers
    - --duration=120m
    - /home/k6/script.js
    volumeMounts:
    - name: k6script
      mountPath: "/home/k6/script.js"
      subPath: script.js
  volumes:
  - name: k6script
    configMap:
      name: k6script
  restartPolicy: Never
